Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-libvirt"
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.network "forwarded_port", guest: 443, host: 8081
  config.vm.provision "shell", path: "install.sh"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 4
    libvirt.nested = true
    libvirt.cpu_mode = "host-model"
  end
end
