blank_issues_enabled: false
contact_links:
  - name: Nextcloud Community Forums
    url: https://help.nextcloud.com/tag/vm
    about: Please visit the community forums for general community discussion, support and the development roadmap.
  - name: Customer Support
    url: https://www.hanssonit.se/#contact
    about: Please contact our customer support for account issues and general customer support.
  - name: Security Issues
    url: https://hackerone.com/nextcloud
    about: We use HackerOne to manage security disclosures.
