version: '3.2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
  app:
    image: nextcloud
    container_name: nc
    restart: always
    ports:
      - ${NC_PORT}:80
    volumes:
      - ./config:/var/www/html/config:rw
      - ${NC_DATADIR}:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=${POSTGRES_DB}
      - POSTGRES_USER_FILE=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER_FILE=${NEXTCLOUD_ADMIN_USER}
    depends_on:
      - db